name: Sync and Publish Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  sync_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check GitHub version
        id: github_version
        run: echo "GITHUB_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Check npm version
        id: npm_version
        run: |
          NPM_VERSION=$(npm view @inkris-apps/inkripto version)
          echo "NPM_VERSION=$NPM_VERSION" >> $GITHUB_ENV

      - name: Sync versions and push to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          while [ "$GITHUB_VERSION" != "$NPM_VERSION" ]; do
            echo "Synchronizing versions..."
            if [ "$(printf '%s\n' "$GITHUB_VERSION" "$NPM_VERSION" | sort -V | head -n1)" = "$GITHUB_VERSION" ]; then
              # GitHub version is behind, update it
              jq ".version=\"$NPM_VERSION\"" package.json > tmp.$$.json && mv tmp.$$.json package.json
              git add package.json
              git commit -m "Sync version with npm registry"
              git push origin main
            else
              # npm version is behind, bump it
              git add -A
              git commit -m "Commit changes before version bump" || echo "No changes to commit"
              npm version patch -m "Bump version to %s"
              git push origin main --follow-tags
            fi
            sleep 5
            GITHUB_VERSION=$(jq -r '.version' package.json)
            NPM_VERSION=$(npm view @inkris-apps/inkripto version)
          done

      - name: Finalize and publish to npm
        if: always()
        run: |
          GITHUB_VERSION=$(jq -r '.version' package.json)
          NPM_VERSION=$(npm view @inkris-apps/inkripto version)
          if [ "$GITHUB_VERSION" == "$NPM_VERSION" ]; then
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
            npm publish --access public
          else
            echo "Versions do not match after synchronization!"
            exit 1
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
